config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items
  patch 'items/:id/update' => "items#update"
  resources :users, only: :show
end

app/models/alcohol.rb
class Alcohol < ActiveHash::Base
  self.data = [
      {id: 1, name: 'ノンアルコール'},
      {id: 2, name: '3％以下'},
      {id: 3, name: '5％'},
      {id: 4, name: '8％前後'},
      {id: 5, name: '12〜18％'},
      {id: 6, name: '19〜22％'},
      {id: 7, name: '25％前後'},
      {id: 8, name: '35％前後'},
      {id: 9, name: '40％以上'},
      {id: 10, name: '不明'},
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item, optional: true
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  validates_associated :images
  validates :item, presence: true
  validates :text, presence: true
  validates :liquor_id, presence: true
  validates :place_id, presence: true
  validates :taste_id, presence: true
  validates :alcohol_id, presence: true
  validates :images, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :liquor
  belongs_to_active_hash :taste
  belongs_to_active_hash :place
  belongs_to_active_hash :alcohol
end

app/models/liquor.rb
class Liquor < ActiveHash::Base
  self.data = [
      {id: 1, name: '日本酒'},
      {id: 2, name: '焼酎'},
      {id: 3, name: 'ビール'},
      {id: 4, name: 'ワイン'},
      {id: 5, name: 'ウイスキー'},
      {id: 6, name: 'ブランデー'},
      {id: 7, name: 'カクテル各種'},
      {id: 8, name: 'その他'},
  ]
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}, {id: 48, name: '外国'},
      {id: 49, name: '不明'}
  ]
end

app/models/taste.rb
class Taste < ActiveHash::Base
  self.data = [
      {id: 1, name: '甘口'},
      {id: 2, name: 'やや甘口'},
      {id: 3, name: '辛口'},
      {id: 4, name: 'やや辛口'},
      {id: 5, name: '飲みやすい'},
      {id: 6, name: '癖がある'},
      {id: 7, name: '香りが良い'},
      {id: 8, name: 'その他'},
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :user, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @items = Item.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @item = Item.new
    @item.images.build
  end

  def create
    @item = Item.new(item_params)
    
    if @item.save
      render :create
    else
      redirect_to new_item_path
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    
    if @item.update(item_params)
      render :update
    else
      redirect_to edit_item_path
    end
  end

  def show
  end

  private
  def item_params
    params.require(:item).permit(
                            :item,
                            :text,
                            :liquor_id,
                            :taste_id,
                            :place_id,
                            :alcohol_id,
                            images_attributes: [:id, :image]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @user = user.user
    @items = user.items.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/create.html.haml
.create-main
  .create-box
    .create-box__titlle
    .create-box__items
      登録が完了しました
      .create-back
        =  link_to('トップページへ戻る',"/items", {class: "create-back__btn"})

app/views/items/destroy.html.haml
.destroy-main
  .destroy-box
    .destroy-box__titlle
    .destroy-box__items
      削除しました
      .destroy-back
        =  link_to('トップページへ戻る',"/items", {class: "destroy-back__btn"})

app/views/items/edit.html.haml
.new-main
  .new-box
    .new-box__titlle
      編集
    .new-box__items
      = form_for @item,url: ("/items/#{@item.id}/update"), class:'new_item' do |f|
        .new-picture
          = f.fields_for :images do |image|
            .new-picture__btn
            = image.file_field :image, class: 'file-box'
            .caution
              画像は改めて選択しない場合前回のものが登録されます
        .new-information
          .new-information__left
            .new-information__left__name
              = f.text_field :item, class: "new-select", placeholder: "酒名", type: "text"
            .new-information__left__liquor
              = f.collection_select( :liquor_id, Liquor.all, :id, :name, {prompt: "種類"}, {class: 'new-select'})
            .new-information__left__place
              = f.collection_select( :place_id, Place.all, :id, :name, {prompt: "産地"}, {class: 'new-select'})
          .new-information__right
            .new-information__right__taste
              = f.collection_select( :taste_id, Taste.all, :id, :name, {prompt: "味"}, {class: 'new-select'})
            .new-information__right__alcohol
              = f.collection_select( :alcohol_id, Alcohol.all, :id, :name, {prompt: "アルコール度数"}, {class: 'new-select'})
            .new-information__right__yobi
          .new-information__text
            = f.text_area :text, class: 'new-remarks', placeholder: '備考'
            = f.submit "編集完了",class:'new-form-btn'

app/views/items/index.html.haml
.top-main
  .top-box
    .top-box__titlle
      最近呑んだお酒
    .top-box__items
      - @items.each do |item|
        .top-item
          .top-item__box
            = image_tag item.images[0].image.url,class: 'top-picture'
            .top-item__name
              = link_to "", item_path(item.id), class: "top-item__name__link"
              = item.item
          - if user_signed_in? && current_user.id == item.user_id
            .edit-box
              = link_to '編集', "/items/#{item.id}/edit", method: :get
            .destroy-box
              = link_to '削除', "/items/#{item.id}", method: :delete
            .top-item-user
              = link_to item.user.user, "/users/#{item.user.id}"
          - else
            .edit-box
            .destroy-box
            .top-item-user
              = link_to item.user.user, "/users/#{item.user.id}"
    .top-paginate= paginate @items
    = link_to "/items/new/", class: "top-new-btn" do
      お酒登録
      .top-new-icon
        .fas.fa-beer.fa-4x
    .top-login
      - if user_signed_in?
        .top-login__box
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        .top-login__box
          = link_to "ログイン", new_user_session_path, class: 'post'
          ／
          = link_to "新規登録", new_user_registration_path, class: 'post'
    .top-mypage
      - if user_signed_in?
        .top-mypage__area
          = link_to "", "/users/#{current_user.id}", class: "top-mypage__area__link"
          .top-mypage__area__user
            = current_user.user
            さんの
          .top-mypage__area__btn
            マイページ
      - else
        .top-mypage__none

app/views/items/new.html.haml
.new-main
  .new-box
    .new-box__titlle
      本日の一杯
    .new-box__items
      = form_for @item,url: items_path, class:'new_item' do |f|
        .new-picture
          = f.fields_for :images do |image|
            .new-picture__btn
            = image.file_field :image, class: 'file-box'
        .new-information
          .new-information__left
            .new-information__left__name
              = f.text_field :item, class: "new-select", placeholder: "酒名", type: "text"
            .new-information__left__liquor
              = f.collection_select( :liquor_id, Liquor.all, :id, :name, {prompt: "種類"}, {class: 'new-select'})
            .new-information__left__place
              = f.collection_select( :place_id, Place.all, :id, :name, {prompt: "産地"}, {class: 'new-select'})
          .new-information__right
            .new-information__right__taste
              = f.collection_select( :taste_id, Taste.all, :id, :name, {prompt: "味"}, {class: 'new-select'})
            .new-information__right__alcohol
              = f.collection_select( :alcohol_id, Alcohol.all, :id, :name, {prompt: "アルコール度数"}, {class: 'new-select'})
            .new-information__right__yobi
          .new-information__text
            = f.text_area :text, class: 'new-remarks', placeholder: '備考'
            = f.submit "登録",class:'new-form-btn'

app/views/items/show.html.haml
.show-main
  .show-box
    .show-box__titlle
      = @item.item
    .show-box__left
      .show-box__left__icon
        %i.fas.fa-glass-martini.fa-8x
    .show-box__items
      .show-picture
        .show-picture__box
          = image_tag @item.images[0].image.url, class: 'show-picture__box__in'
      .show-information
        .show-information__day
          吞んだ日 : 
          = @item.images[0].created_at.strftime("%Y/%m/%d  %a  %H:%M")
        .show-information__liquor
          お酒の種類 : #{@item.liquor.name}
        .show-information__place
          産地 : #{@item.place.name}
        .show-information__alcohol
          アルコール度数 : #{@item.alcohol.name}
        .show-information__taste
          味・特徴 : #{@item.taste.name}
      .show-text
        = simple_format @item.text
    .show-box__right
      .show-box__right__icon
        %i.fas.fa-beer.fa-9x
    .show-back
      = link_to 'トップへ戻る','/',class: 'show-back__btn'

app/views/items/update.html.haml
.update-main
  .update-box
    .update-box__titlle
    .update-box__items
      編集が完了しました
      .update-back
        =  link_to('トップページへ戻る',"/", {class: "update-back__btn"})

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ばっかす
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://use.fontawesome.com/releases/v5.0.10/css/all.css", :rel => "stylesheet"}/
  %body
    #wrapper
      .header
      = image_tag "beer.png", class: "header__img"
      = link_to "ばっかす", "/", class: "header__titlle"
      = yield
      %footer.footer
        = image_tag "sashimi.png", class: "footer__img-left"
        = image_tag "edamame.png", class: "footer__img-center"
        = image_tag "karaage.png", class: "footer__img-right"
        .footer__logo
          © ばっかす 2020

app/views/users/show.html.haml
.top-main
  .top-box
    .top-box__titlle
      = @user
      さんの飲酒履歴
    .top-box__items
      - @items.each do |item|
        .top-item
          .top-item__box
            = image_tag item.images[0].image.url,class: 'top-picture'
            .top-item__name
              = link_to "", item_path(item.id), class: "top-item__name__link"
              = item.item
          - if user_signed_in? && current_user.id == item.user_id
            .edit-box
              = link_to '編集', "/items/#{item.id}/edit", method: :get
            .destroy-box
              = link_to '削除', "/items/#{item.id}", method: :delete
          - else
            .edit-box
            .destroy-box
    .top-paginate= paginate @items
    = link_to "/items/new/", class: "top-new-btn" do
      お酒登録
      .top-new-icon
        .fas.fa-beer.fa-4x